export const legalCategories = {
  '1000': 'Personne physique',
  '5498': 'SARL unipersonnelle',
  '5485': 'SARL (Société à responsabilité limitée)',
  '5710': 'SAS (Société par actions simplifiée)',
  '5720': 'SA (Société anonyme)',
  '5785': 'SASU (SAS unipersonnelle)',
  '6200': 'Groupement d\'intérêt économique (GIE)',
  '9220': 'Association déclarée',
  '9210': 'Association non déclarée',
  '7210': 'Société civile',
  '7300': 'Société civile professionnelle',
  '7215': 'SCP (Société civile de moyens)',
  '8310': 'Groupement agricole d\'exploitation en commun (GAEC)',
  '9300': 'Organisme de droit étranger',
  '7312': 'Société civile immobilière (SCI)',
  '7311': 'Société civile immobilière de construction-vente (SCCV)',
  '6410': 'Société en nom collectif (SNC)',
  '6420': 'Société en commandite simple',
  '6430': 'Société en commandite par actions',
  '5499': 'Autres sociétés commerciales',
  '5700': 'Société par actions',
  '6900': 'Société coopérative',
  '8600': 'Syndicat de copropriété',
  '9110': 'Collectivité territoriale',
  '9120': 'Établissement public administratif',
  '9130': 'Établissement public industriel et commercial',
  '9140': 'Organisme consulaire',
  '9150': 'Établissement public local d’enseignement',
  '9900': 'Autre personne morale de droit public',
  '7212': 'Société civile d\'exploitation agricole (SCEA)',
  '7217': 'Société civile professionnelle (SCP)',
  '7340': 'Société civile de portefeuille',
  '7346': 'Société civile de placement immobilier (SCPI)',
  '5497': 'EURL (Entreprise unipersonnelle à responsabilité limitée)',
  '5724': 'SA à directoire et conseil de surveillance',
  '5725': 'SA à conseil d’administration',
  '6100': 'Société coopérative agricole',
  '9111': 'Commune',
  '9112': 'Département',
  '9113': 'Région',
  '9114': 'Collectivité d\'outre-mer',
}
