export const legalCategories = {
  '1000': 'Personne physique',
  '1100': 'Artisan-commerçant',
  '1200': 'Commerçant',
  '1300': 'Artisan',
  '1400': 'Officier public ou ministériel',
  '1500': 'Profession libérale',
  '1600': 'Exploitant agricole',
  '1700': 'Agent commercial',
  '1800': 'Associé gérant de Société',
  '1900': '(Autre) Personne physique',
  '2110': 'Indivision entre personnes physiques',
  '2120': 'Indivision avec personne morale',
  '2210': 'Société créée de fait entre personnes physiques',
  '2220': 'Société créée de fait avec personne morale',
  '2310': 'Société en participation entre personnes physiques',
  '2320': 'Société en participation avec personne morale',
  '2385': 'Société en participation de professions libérales',
  '2400': 'Fiducie',
  '2700': 'Paroisse hors zone concordataire',
  '2900': 'Autre groupement de droit privé non doté de la personnalité morale',
  '3110': 'Représentation ou agence commerciale d\'état ou organisme public étranger immatriculé au RCS',
  '3120': 'Société commerciale étrangère immatriculée au RCS',
  '3205': 'Organisation internationale',
  '3210': 'État, collectivité ou établissement public étranger',
  '3220': 'Société étrangère non immatriculée au RCS',
  '3290': 'Autre personne morale de droit étranger',
  '4110': 'Établissement public national à caractère industriel ou commercial doté d\'un comptable public',
  '4120': 'Établissement public national à caractère industriel ou commercial non doté d\'un comptable public',
  '5599': 'Société d\'exercice libéral par actions simplifiée (SELA)',
  '5100': 'Société anonyme (SA)',
  '5200': 'Société par actions simplifiée (SAS)',
  '5300': 'Société à responsabilité limitée (SARL)',
  '5400': 'Société en nom collectif (SNC)',
  '5500': 'Société en commandite simple (SCS)',
  '5510': 'Société en commandite par actions (SCA)',
  '5580': 'Société civile',
  '5590': 'Société civile professionnelle (SCP)',
  '5598': 'Société d\'exercice libéral à responsabilité limitée (SELARL)',
  '5600': 'Association',
  '5700': 'Coopérative',
  '5800': 'Groupement d\'intérêt économique (GIE)',
  '5900': 'Autres formes juridiques',
}
